---
- name: Register Cluster State
  slurp:
    src: /opt/kubespray_state.json
  register: cluster_state
  delegate_to: localhost

- name: Set Facts for repo
  set_fact:
    registry_facts: "{{ (cluster_state['content'] | b64decode | from_json).docker_registry }}"

- name: Deploy private registry secrets
  include_tasks: apply_k8s_object.yml
  with_items:
    - registry_secrets.yaml.j2
    - registry_pvc.yaml.j2
    - registry_deployment.yaml.j2
